apiVersion: v2
appVersion: v1.1.2
name: synology-csi
description: A Helm chart for the Synology CSI Driver
keywords:
  - Synology
  - CSI Driver
kubeVersion: ">= 1.20.0"
sources:
  - https://github.com/christian-schlichtherle/synology-csi-chart/tree/main
  - https://github.com/SynologyOpenSource/synology-csi/tree/main
version: 0.9.3-SNAPSHOT # must be SemVer 2
